---
title: "Wine Quality"
author: "Alexandre SALMON, Thomas FRION"
date: "13/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggplot2")
library("reshape2")
library("GGally")
library("fpc")

```

```{r}
# Get Data
red_wine<-read.csv("data/winequality-red.csv", fill = TRUE, sep=";")
white_wine<-read.csv("data/winequality-white.csv", fill = TRUE, sep=";")
```

```{r}
white_wine['type']='White'
red_wine['type']='Red'
all_wine<-rbind(red_wine, white_wine)
all_wine.m <- melt(all_wine, id.var = "type")

p <- ggplot(data = all_wine.m, aes(x=variable, y=value)) 
p <- p + geom_boxplot(aes(fill=type))
p <- p + facet_wrap( ~ variable, scales="free")
p <- p + xlab("") + ylab("") + ggtitle("Composition des vins en fonction du Type")
p <- p + guides(fill=guide_legend(title="Type de vin"))
p 

```

```{r}
all_wine5050 <- rbind(white_wine[sample(nrow(white_wine), 1000), ], red_wine[sample(nrow(red_wine), 1000), ])
ggcorr(all_wine5050[, -1], geom = "blank", label = TRUE, hjust = 0.75) +
  geom_point(size = 10, aes(color = coefficient > 0, alpha = abs(coefficient) > 0.5)) +
  scale_alpha_manual(values = c("TRUE" = 0.25, "FALSE" = 0)) +
  guides(color = FALSE, alpha = FALSE)


ggcorr(red_wine[, -1], geom = "blank", label = TRUE, hjust = 0.75) +
  geom_point(size = 10, aes(color = coefficient > 0, alpha = abs(coefficient) > 0.5)) +
  scale_alpha_manual(values = c("TRUE" = 0.25, "FALSE" = 0)) +
  guides(color = FALSE, alpha = FALSE)


ggcorr(white_wine[, -1], geom = "blank", label = TRUE, hjust = 0.75) +
  geom_point(size = 10, aes(color = coefficient > 0, alpha = abs(coefficient) > 0.5)) +
  scale_alpha_manual(values = c("TRUE" = 0.25, "FALSE" = 0)) +
  guides(color = FALSE, alpha = FALSE)
```

```{r}

allWineSelection <- all_wine5050[sample(nrow(all_wine5050), 50), 1:11]
plot(allWineSelection, main = "Plot of Wines")

allWineSelection1 <- all_wine5050[sample(nrow(all_wine5050), 50), c(4, 6, 7, 8, 11)]
plot(allWineSelection1, main = "Plot of Wines")

redWineSelection <- all_wine5050[1:50, 1:11]
plot(redWineSelection, main = "Plot of Red Wines")

redWineSelection1 <- red_wine[1:50, c(2, 3, 6, 7, 9)]
plot(redWineSelection1, main = "Plot of Red Wines")

whiteWineSelection <- white_wine[1:50, 1:11]
plot(whiteWineSelection, main = "Plot of White Wines")

whiteWineSelection1 <- white_wine[1:50, c(4 ,6, 7, 8, 11)]
plot(whiteWineSelection1, main = "Plot of White Wines")

```


```{r}
all_wine5050$type<-NULL

arr = c()
for (i in 1:15) {
  res <- kmeans(all_wine5050,i)
  arr<-c(arr,res$tot.withinss/res$totss)
}

plot(arr)
white_wine
white_wine$type<-NULL

whiteWineClus <- kmeans(white_wine, 4)
plotcluster(white_wine, whiteWineClus$cluster)
with(white_wine, pairs(white_wine, col=c(1:3)[whiteWineClus$cluster])) 
```

